More classes to hooks
cirruslabs/cirrus-ci-web pull request #297
Opened 2020-10-01 21:21 UTC by RDIL

I'm going to do more of this later.  

Signed-off-by: Reece Dunham <me@rdil.rocks>

2020-10-01 22:29 UTC, RDIL commented
@fkorotkov any idea why the pod failed?

2020-10-02 13:58 UTC, fkorotkov reviewed
Clickin on Settings doesn't work for me on your fork: nothing happens

2020-10-02 14:06 UTC, RDIL commented
I'll investigate.

2020-10-02 16:47 UTC, RDIL commented
Fixed.

2020-10-05 17:18 UTC, RDIL commented
@fkorotkov review ping.

2020-10-05 20:36 UTC, fkorotkov requested changes

2020-10-05 20:36 UTC, fkorotkov commented on src/components/chips/BuildCreatedChip.tsx
> +        className={this.props.className}
```suggestion
        className={props.className}
```

2020-10-06 10:50 UTC, fkorotkov approved these changes

2020-10-06 10:50 UTC, merged